language: java
sudo: false
addons:
  apt:
    update:
      - true
    packages:
      - openjdk-6-jdk
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7
  - openjdk6
notifications:
  irc: "irc.freenode.org#asciidoctor"
