== AsciiDoclet

An Asciidoc Javadoc Doclet which allows you to write Javadocs in Asciidoc format.

Traditionally, Javadocs have mixed minor markup with html which, if you're writing for html Javadoc output, becomes
unreadable and hard to write over time.  This is where lightweight markup languages like Asciidoc thrive.  Asciidoc
straddles the line between readable markup and beautifully rendered content.

AsciiDoclet encorporates an Asciidoc renderer
(https://github.com/asciidoctor/asciidoctor[asciidoctor] via
https://github.com/asciidoctor/asciidoctor-java-integration[asciidoctor-java-integration])
into a simple Doclet that enables Asciidoc formatting within javadoc comments and tags.

=== Example

Here's an example of a class with traditional javadoc:
[code,java]
----
/**
 * <h2>Asciidoclet</h2>
 *
 * <p>Sample Comments including {@code source}</p>
 *
 * <pre>{@code
 * public class Asciidoclet{
 *     public Asciidoclet(){}
 * }
 * }</pre>
 */
public class Asciidoclet extends Doclet  {}
----

and here's the same class with AsciiDoclet:

[code,java]
----
/**
 * Asciidoclet
 * ------------
 * Sample Comments including 'source'
 *
 * [code,java]
 * ----
 * public class Asciidoclet{
 *     public Asciidoclet(){}
 * }
 * ----
 */
public class Asciidoclet extends Doclet  {}
----

The result is readable source and beautifully rendered javadocs, the best of both worlds!

=== Usage
AsciiDoclet may be used via a maven-javadoc-plugin doclet:
[code,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-javadoc-plugin</artifactId>
    <version>2.9</version>
    <configuration>
        <source>1.7</source>
        <doclet>org.asciidoclet.Asciidoclet</doclet>
        <docletArtifact>
            <groupId>org.asciidoclet</groupId>
            <artifactId>asciidoclet</artifactId>
            <version>${asciidoclet.version}</version>
        </docletArtifact>
    </configuration>
</plugin>
----

=== Licsense

[code]
----
Copyright 2013 John Ericksen

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
----