= Usage
:asciidoclet-class: org.asciidoctor.asciidoclet.Asciidoclet
:maven-javadoc-plugin-version: 3.6.3

Run Javadoc with the `{asciidoclet-class}` doclet class as shown in the examples below.
See
ifdef::site-gen-antora[xref:options.adoc[]]
ifndef::site-gen-antora[<<doclet-options>> below]
for supported options.

NOTE: Asciidoclet must use some Java runtime internals.
That requires the use of `exports` and `open` configurations depending on the Java version in use.

== Maven

Asciidoclet may be used via a `maven-javadoc-plugin` for the supported Java versions.
Pay special attention to `<additionalJOptions>` to configure access to Java internals.

== Java 11 example

[source,xml,subs="attributes+"]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-javadoc-plugin</artifactId>
    <version>{maven-javadoc-plugin-version}</version>
    <configuration>
        <source>11</source>
        <doclet>{asciidoclet-class}</doclet>
        <docletArtifact>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoclet</artifactId>
            <version>{asciidoclet-version}</version>
        </docletArtifact>
        <overview>src/main/java/overview.adoc</overview>
        <additionalparam>
          --base-dir ${project.basedir}
          --attribute "name=${project.name}"
          --attribute "version=${project.version}"
          --attribute "title-link=https://example.com[${project.name} ${project.version}]"
        </additionalparam>
        <additionalJOptions>
            <additionalJOption>-J--add-exports=jdk.javadoc/jdk.javadoc.internal.tool=ALL-UNNAMED</additionalJOption>
            <additionalJOption>-Xdoclint:all,-html,-accessibility</additionalJOption>
        </additionalJOptions>
    </configuration>
</plugin>
----

== Java 17+ example

[source,xml,subs="attributes+"]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-javadoc-plugin</artifactId>
    <version>{maven-javadoc-plugin-version}</version>
    <configuration>
        <source>17</source>
        <doclet>{asciidoclet-class}</doclet>
        <docletArtifact>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoclet</artifactId>
            <version>{asciidoclet-version}</version>
        </docletArtifact>
        <overview>src/main/java/overview.adoc</overview>
        <additionalparam>
          --base-dir ${project.basedir}
          --attribute "name=${project.name}"
          --attribute "version=${project.version}"
          --attribute "title-link=https://example.com[${project.name} ${project.version}]"
        </additionalparam>
        <additionalJOptions>
            <additionalJOption>-J--add-exports=jdk.javadoc/jdk.javadoc.internal.tool=ALL-UNNAMED</additionalJOption>
            <additionalJOption>-J--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</additionalJOption>
            <additionalJOption>-J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED</additionalJOption>
            <additionalJOption>-J--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED</additionalJOption>
            <additionalJOption>-J--add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED</additionalJOption>
            <additionalJOption>-J--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</additionalJOption>
            <additionalJOption>-Xdoclint:all,-html,-accessibility</additionalJOption>
        </additionalJOptions>
    </configuration>
</plugin>
----

== Gradle

Asciidoclet may be used via a doclet in the `Javadoc` task:
Pay special attention to `jFlags` to configure access to Java internals.

== Java 11 example

[source,groovy,subs="attributes+"]
----
plugins {
    id 'java'
}

configurations {
    asciidoclet
}

dependencies {
    asciidoclet 'org.asciidoctor:asciidoclet:{asciidoclet-version}'
}

javadoc {
    options {
        docletpath = configurations.asciidoclet.files.asType(List)
        doclet = '{asciidoclet-class}'
        overview = "src/main/java/overview.adoc"
        addStringOption "-base-dir", "$\{projectDir}" // <1>
        addStringOption \
            "-attribute", // <2>
                "name=${project.name}," +
                "version=${project.version}," +
                "title-link=https://example.com[${project.name} ${project.version}]"
        jFlags \
            "--add-exports=jdk.javadoc/jdk.javadoc.internal.tool=ALL-UNNAMED"
    }
}
----
<1> Option names passed to Gradle's `javadoc` task must omit the leading "-", so here "-base-dir" means "--base-dir".
ifdef::site-gen-antora[See xref:options.adoc[].]
ifndef::site-gen-antora[See <<doclet-options>> below.]
<2> Gradle's `javadoc` task does not allow multiple occurrences of the same option.
Multiple attributes can be specified in a single string, separated by commas.

== Java 17+ example

[source,groovy,subs="attributes+"]
----
plugins {
    id 'java'
}

configurations {
    asciidoclet
}

dependencies {
    asciidoclet 'org.asciidoctor:asciidoclet:{asciidoclet-version}'
}

javadoc {
    options {
        docletpath = configurations.asciidoclet.files.asType(List)
        doclet = '{asciidoclet-class}'
        overview = "src/main/java/overview.adoc"
        addStringOption "-base-dir", "$\{projectDir}" // <1>
        addStringOption \
            "-attribute", // <2>
                "name=${project.name}," +
                "version=${project.version}," +
                "title-link=https://example.com[${project.name} ${project.version}]"
        jFlags \
            "--add-exports=jdk.javadoc/jdk.javadoc.internal.tool=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED",
            "--add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
            "--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED"
    }
}
----
<1> Option names passed to Gradle's `javadoc` task must omit the leading "-", so here "-base-dir" means "--base-dir".
ifdef::site-gen-antora[See xref:options.adoc[].]
ifndef::site-gen-antora[See <<doclet-options>> below.]
<2> Gradle's `javadoc` task does not allow multiple occurrences of the same option.
Multiple attributes can be specified in a single string, separated by commas.
